--ALL SPONSORS WHO SPONSOR JAPANESE TEAMS AND PRODUCE TUNA
SELECT S.SPONSOR_NAME, S.PRODUCT, S.OFFICE_ADDRESS
FROM CHASHKEN.SPONSOR S
WHERE S.SPONSORID IN (SELECT SB.SPONSORID
FROM CHASHKEN.SPONSORED_BY SB
WHERE SB.TEAMID IN (SELECT T1.TEAMID 
FROM CHASHKEN.TEAM T1, CHASHKEN.STADIUM S1 
WHERE S1.COUNTRY='Japan'))
AND S.PRODUCT='Tuna';
